@startuml
    class Projects {
        - id: unique int
        + **organization**: ref to **Organizations**
        + project_id: unique str
        + name: str
        + description: str
        + configs: json dict
        + rules: json dict
    }
@enduml
